name: Build with Maven and deploy to Google Cloud Run

on:
  push:
    branches: [ main ]

jobs:

  build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1.1.1
      with:
        workload_identity_provider: projects/547168271352/locations/global/workloadIdentityPools/my-pool/providers/my-provider
        service_account: my-service-account@test-secret-402616.iam.gserviceaccount.com

    - name: Build with Maven and push image using Jib
      run: mvn compile jib:build

    - name: Deploy to Google Cloud Run
      run: gcloud run deploy demo-app --image=gcr.io/test-secret-402616/demo:latest --platform managed --region us-central1 --allow-unauthenticated